/**
 * Charades prompts organized by category
 * Each prompt has a text and difficulty (1=easy, 2=medium, 3=hard)
 */

export const CATEGORIES = {
  MOVIES: "Movies & TV",
  ACTIONS: "Actions",
  ANIMALS: "Animals",
  OCCUPATIONS: "Occupations",
  SPORTS: "Sports & Activities",
  OBJECTS: "Objects",
  FAMOUS: "Famous People",
  PHRASES: "Phrases & Sayings",
};

export const PROMPTS = [
  // Movies & TV
  { text: "Star Wars", category: "MOVIES", difficulty: 1 },
  { text: "Titanic", category: "MOVIES", difficulty: 1 },
  { text: "Harry Potter", category: "MOVIES", difficulty: 1 },
  { text: "The Lion King", category: "MOVIES", difficulty: 1 },
  { text: "Frozen", category: "MOVIES", difficulty: 1 },
  { text: "Jaws", category: "MOVIES", difficulty: 1 },
  { text: "E.T.", category: "MOVIES", difficulty: 1 },
  { text: "Spider-Man", category: "MOVIES", difficulty: 1 },
  { text: "Batman", category: "MOVIES", difficulty: 1 },
  { text: "Jurassic Park", category: "MOVIES", difficulty: 1 },
  { text: "Finding Nemo", category: "MOVIES", difficulty: 1 },
  { text: "The Matrix", category: "MOVIES", difficulty: 2 },
  { text: "Ghostbusters", category: "MOVIES", difficulty: 1 },
  { text: "Indiana Jones", category: "MOVIES", difficulty: 2 },
  { text: "Forrest Gump", category: "MOVIES", difficulty: 2 },
  { text: "The Wizard of Oz", category: "MOVIES", difficulty: 2 },
  { text: "Home Alone", category: "MOVIES", difficulty: 1 },
  { text: "Shrek", category: "MOVIES", difficulty: 1 },
  { text: "The Avengers", category: "MOVIES", difficulty: 1 },
  { text: "Game of Thrones", category: "MOVIES", difficulty: 2 },
  { text: "Breaking Bad", category: "MOVIES", difficulty: 2 },
  { text: "Friends", category: "MOVIES", difficulty: 1 },
  { text: "The Office", category: "MOVIES", difficulty: 2 },
  { text: "Stranger Things", category: "MOVIES", difficulty: 2 },
  { text: "Toy Story", category: "MOVIES", difficulty: 1 },

  // Actions
  { text: "Brushing teeth", category: "ACTIONS", difficulty: 1 },
  { text: "Taking a selfie", category: "ACTIONS", difficulty: 1 },
  { text: "Riding a bicycle", category: "ACTIONS", difficulty: 1 },
  { text: "Swimming", category: "ACTIONS", difficulty: 1 },
  { text: "Dancing", category: "ACTIONS", difficulty: 1 },
  { text: "Sleeping", category: "ACTIONS", difficulty: 1 },
  { text: "Eating spaghetti", category: "ACTIONS", difficulty: 1 },
  { text: "Playing guitar", category: "ACTIONS", difficulty: 1 },
  { text: "Driving a car", category: "ACTIONS", difficulty: 1 },
  { text: "Cooking", category: "ACTIONS", difficulty: 1 },
  { text: "Taking a shower", category: "ACTIONS", difficulty: 1 },
  { text: "Bowling", category: "ACTIONS", difficulty: 1 },
  { text: "Fishing", category: "ACTIONS", difficulty: 1 },
  { text: "Skipping rope", category: "ACTIONS", difficulty: 1 },
  { text: "Blowing bubbles", category: "ACTIONS", difficulty: 1 },
  { text: "Opening a present", category: "ACTIONS", difficulty: 1 },
  { text: "Sneezing", category: "ACTIONS", difficulty: 1 },
  { text: "Yawning", category: "ACTIONS", difficulty: 1 },
  { text: "Texting", category: "ACTIONS", difficulty: 1 },
  { text: "Juggling", category: "ACTIONS", difficulty: 2 },
  { text: "Walking a tightrope", category: "ACTIONS", difficulty: 2 },
  { text: "Surfing", category: "ACTIONS", difficulty: 1 },
  { text: "Skiing", category: "ACTIONS", difficulty: 1 },
  { text: "Rock climbing", category: "ACTIONS", difficulty: 2 },
  { text: "Hula hooping", category: "ACTIONS", difficulty: 1 },

  // Animals
  { text: "Elephant", category: "ANIMALS", difficulty: 1 },
  { text: "Monkey", category: "ANIMALS", difficulty: 1 },
  { text: "Snake", category: "ANIMALS", difficulty: 1 },
  { text: "Penguin", category: "ANIMALS", difficulty: 1 },
  { text: "Kangaroo", category: "ANIMALS", difficulty: 1 },
  { text: "Giraffe", category: "ANIMALS", difficulty: 1 },
  { text: "Lion", category: "ANIMALS", difficulty: 1 },
  { text: "Chicken", category: "ANIMALS", difficulty: 1 },
  { text: "Dog", category: "ANIMALS", difficulty: 1 },
  { text: "Cat", category: "ANIMALS", difficulty: 1 },
  { text: "Fish", category: "ANIMALS", difficulty: 1 },
  { text: "Butterfly", category: "ANIMALS", difficulty: 1 },
  { text: "Spider", category: "ANIMALS", difficulty: 1 },
  { text: "Frog", category: "ANIMALS", difficulty: 1 },
  { text: "Gorilla", category: "ANIMALS", difficulty: 1 },
  { text: "Bear", category: "ANIMALS", difficulty: 1 },
  { text: "Rabbit", category: "ANIMALS", difficulty: 1 },
  { text: "Owl", category: "ANIMALS", difficulty: 1 },
  { text: "Shark", category: "ANIMALS", difficulty: 1 },
  { text: "Dolphin", category: "ANIMALS", difficulty: 1 },
  { text: "Flamingo", category: "ANIMALS", difficulty: 2 },
  { text: "Sloth", category: "ANIMALS", difficulty: 2 },
  { text: "Peacock", category: "ANIMALS", difficulty: 2 },
  { text: "Octopus", category: "ANIMALS", difficulty: 2 },
  { text: "Crocodile", category: "ANIMALS", difficulty: 1 },

  // Occupations
  { text: "Doctor", category: "OCCUPATIONS", difficulty: 1 },
  { text: "Firefighter", category: "OCCUPATIONS", difficulty: 1 },
  { text: "Police officer", category: "OCCUPATIONS", difficulty: 1 },
  { text: "Chef", category: "OCCUPATIONS", difficulty: 1 },
  { text: "Teacher", category: "OCCUPATIONS", difficulty: 1 },
  { text: "Pilot", category: "OCCUPATIONS", difficulty: 1 },
  { text: "Astronaut", category: "OCCUPATIONS", difficulty: 1 },
  { text: "Dentist", category: "OCCUPATIONS", difficulty: 1 },
  { text: "Magician", category: "OCCUPATIONS", difficulty: 1 },
  { text: "Photographer", category: "OCCUPATIONS", difficulty: 1 },
  { text: "DJ", category: "OCCUPATIONS", difficulty: 1 },
  { text: "Cowboy", category: "OCCUPATIONS", difficulty: 1 },
  { text: "Ninja", category: "OCCUPATIONS", difficulty: 1 },
  { text: "Pirate", category: "OCCUPATIONS", difficulty: 1 },
  { text: "Superhero", category: "OCCUPATIONS", difficulty: 1 },
  { text: "Ballet dancer", category: "OCCUPATIONS", difficulty: 2 },
  { text: "Mime", category: "OCCUPATIONS", difficulty: 2 },
  { text: "Lifeguard", category: "OCCUPATIONS", difficulty: 1 },
  { text: "Zookeeper", category: "OCCUPATIONS", difficulty: 2 },
  { text: "Gardener", category: "OCCUPATIONS", difficulty: 1 },

  // Sports & Activities
  { text: "Basketball", category: "SPORTS", difficulty: 1 },
  { text: "Soccer", category: "SPORTS", difficulty: 1 },
  { text: "Tennis", category: "SPORTS", difficulty: 1 },
  { text: "Golf", category: "SPORTS", difficulty: 1 },
  { text: "Boxing", category: "SPORTS", difficulty: 1 },
  { text: "Wrestling", category: "SPORTS", difficulty: 1 },
  { text: "Ice skating", category: "SPORTS", difficulty: 1 },
  { text: "Yoga", category: "SPORTS", difficulty: 1 },
  { text: "Karate", category: "SPORTS", difficulty: 1 },
  { text: "Baseball", category: "SPORTS", difficulty: 1 },
  { text: "Volleyball", category: "SPORTS", difficulty: 1 },
  { text: "Archery", category: "SPORTS", difficulty: 2 },
  { text: "Weightlifting", category: "SPORTS", difficulty: 1 },
  { text: "Skateboarding", category: "SPORTS", difficulty: 1 },
  { text: "Snowboarding", category: "SPORTS", difficulty: 1 },
  { text: "Horse riding", category: "SPORTS", difficulty: 1 },
  { text: "Gymnastics", category: "SPORTS", difficulty: 2 },
  { text: "Fencing", category: "SPORTS", difficulty: 2 },
  { text: "Table tennis", category: "SPORTS", difficulty: 1 },
  { text: "Diving", category: "SPORTS", difficulty: 1 },

  // Objects
  { text: "Umbrella", category: "OBJECTS", difficulty: 1 },
  { text: "Camera", category: "OBJECTS", difficulty: 1 },
  { text: "Microwave", category: "OBJECTS", difficulty: 1 },
  { text: "Blender", category: "OBJECTS", difficulty: 1 },
  { text: "Vacuum cleaner", category: "OBJECTS", difficulty: 1 },
  { text: "Chainsaw", category: "OBJECTS", difficulty: 2 },
  { text: "Roller coaster", category: "OBJECTS", difficulty: 2 },
  { text: "Helicopter", category: "OBJECTS", difficulty: 1 },
  { text: "Rocket ship", category: "OBJECTS", difficulty: 1 },
  { text: "Trampoline", category: "OBJECTS", difficulty: 1 },
  { text: "Escalator", category: "OBJECTS", difficulty: 2 },
  { text: "Scissors", category: "OBJECTS", difficulty: 1 },
  { text: "Telephone", category: "OBJECTS", difficulty: 1 },
  { text: "Mirror", category: "OBJECTS", difficulty: 1 },
  { text: "Balloon", category: "OBJECTS", difficulty: 1 },
  { text: "Lawnmower", category: "OBJECTS", difficulty: 2 },
  { text: "Washing machine", category: "OBJECTS", difficulty: 1 },
  { text: "Piano", category: "OBJECTS", difficulty: 1 },
  { text: "Drums", category: "OBJECTS", difficulty: 1 },
  { text: "Candle", category: "OBJECTS", difficulty: 1 },

  // Famous People / Characters
  { text: "Elvis Presley", category: "FAMOUS", difficulty: 2 },
  { text: "Michael Jackson", category: "FAMOUS", difficulty: 1 },
  { text: "Beyonce", category: "FAMOUS", difficulty: 2 },
  { text: "Donald Duck", category: "FAMOUS", difficulty: 1 },
  { text: "Mickey Mouse", category: "FAMOUS", difficulty: 1 },
  { text: "Superman", category: "FAMOUS", difficulty: 1 },
  { text: "Darth Vader", category: "FAMOUS", difficulty: 1 },
  { text: "Yoda", category: "FAMOUS", difficulty: 2 },
  { text: "Tarzan", category: "FAMOUS", difficulty: 1 },
  { text: "Dracula", category: "FAMOUS", difficulty: 1 },
  { text: "Frankenstein", category: "FAMOUS", difficulty: 2 },
  { text: "James Bond", category: "FAMOUS", difficulty: 2 },
  { text: "Santa Claus", category: "FAMOUS", difficulty: 1 },
  { text: "The Hulk", category: "FAMOUS", difficulty: 1 },
  { text: "Wonder Woman", category: "FAMOUS", difficulty: 1 },
  { text: "Sherlock Holmes", category: "FAMOUS", difficulty: 2 },
  { text: "King Kong", category: "FAMOUS", difficulty: 1 },
  { text: "Godzilla", category: "FAMOUS", difficulty: 2 },
  { text: "Cinderella", category: "FAMOUS", difficulty: 1 },
  { text: "Pinocchio", category: "FAMOUS", difficulty: 2 },

  // Phrases & Sayings
  { text: "Break a leg", category: "PHRASES", difficulty: 2 },
  { text: "Raining cats and dogs", category: "PHRASES", difficulty: 2 },
  { text: "Piece of cake", category: "PHRASES", difficulty: 2 },
  { text: "Couch potato", category: "PHRASES", difficulty: 2 },
  { text: "Night owl", category: "PHRASES", difficulty: 2 },
  { text: "Cold feet", category: "PHRASES", difficulty: 2 },
  { text: "Butterflies in stomach", category: "PHRASES", difficulty: 2 },
  { text: "Walking on eggshells", category: "PHRASES", difficulty: 3 },
  { text: "Cry over spilled milk", category: "PHRASES", difficulty: 3 },
  { text: "Let the cat out of the bag", category: "PHRASES", difficulty: 3 },
  { text: "Fish out of water", category: "PHRASES", difficulty: 2 },
  { text: "Hit the hay", category: "PHRASES", difficulty: 2 },
  { text: "Under the weather", category: "PHRASES", difficulty: 2 },
  { text: "Hot potato", category: "PHRASES", difficulty: 2 },
  { text: "Dark horse", category: "PHRASES", difficulty: 3 },
];

export function getRandomPrompt(usedPrompts = []) {
  const available = PROMPTS.filter((p) => !usedPrompts.includes(p.text));
  if (available.length === 0) {
    // Reset if all prompts used
    return PROMPTS[Math.floor(Math.random() * PROMPTS.length)];
  }
  return available[Math.floor(Math.random() * available.length)];
}

export function getCategoryName(category) {
  return CATEGORIES[category] || category;
}
